name: Deploy INST-377-final-project to Vercel

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch
  pull_request:
    branches:
      - main  # Optional: Deploy previews on pull requests to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Use the Node.js version required by your project

    - name: Install Dependencies
      run: npm install
      
    - name: Install Vercel  
      run: npm install -g vercel

    - name: Deploy to Vercel
      run: npx vercel --prod --yes --token=qZabIfM33UosXhYLxAB0JnAg

